const audio=document.getElementById('audio'),play=document.getElementById('play'),prev=document.getElementById('prev'),next=document.getElementById('next'),seek=document.getElementById('seek'),volume=document.getElementById('volume'),volTxt=document.getElementById('volTxt'),timeNow=document.getElementById('timeNow'),timeTotal=document.getElementById('timeTotal'),nowTitle=document.getElementById('nowTitle'),nowArtist=document.getElementById('nowArtist'),msg=document.getElementById('msg'),state=document.getElementById('state'),playlistEl=document.getElementById('playlist'),fileInput=document.getElementById('fileInput'),themeBtn=document.getElementById('themeBtn'),eqWrap=document.getElementById('eq'),dropzone=document.getElementById('dropzone'),dropBar=document.getElementById('dropBar'),searchFilter=document.getElementById('searchFilter'),body=document.body;
let theme='dark',playlist=[],current=-1,audioCtx,sourceNode,filters=[]; const bands=[60,170,350,1000,3500];
function fmt(t){if(!isFinite(t))return'0:00';const m=Math.floor(t/60),s=Math.floor(t%60).toString().padStart(2,'0');return`${m}:${s}`}
function setMsg(text,ok=true){msg.textContent=text;msg.className='status '+(ok?'good':'bad');state.textContent=ok?'Ready':'Issue'}
function ensureCtx(){if(audioCtx)return;audioCtx=new (window.AudioContext||window.webkitAudioContext)();sourceNode=audioCtx.createMediaElementSource(audio);filters=bands.map(f=>{const b=audioCtx.createBiquadFilter();b.type='peaking';b.frequency.value=f;b.Q.value=1.1;b.gain.value=0;return b});filters.reduce((p,f)=>{p.connect(f);return f},sourceNode).connect(audioCtx.destination)}
function renderEq(){eqWrap.innerHTML='';bands.forEach((f,i)=>{const row=document.createElement('div');row.className='band';row.innerHTML=`<label>${f} Hz</label><input type="range" min="-12" max="12" value="0" step="1"><span>0 dB</span>`;const range=row.querySelector('input'),txt=row.querySelector('span');range.addEventListener('input',()=>{ensureCtx();filters[i].gain.value=Number(range.value);txt.textContent=`${range.value} dB`});eqWrap.appendChild(row)})}
function filteredPlaylist(){const q=searchFilter.value.trim().toLowerCase();return playlist.filter(t=>!q||(t.title+' '+(t.artist||'')).toLowerCase().includes(q))}
function thumbSVG(){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="9" cy="16" r="2.5"/><path d="M11.5 16V5l9-2v11"/><path d="M11.5 7l9-2"/></svg>`}
function renderPlaylist(){playlistEl.innerHTML='';const items=filteredPlaylist();items.forEach(t=>{const i=playlist.indexOf(t),wrap=document.createElement('div');wrap.className='track'+(i===current?' active':'')+(i===current&&audio&&!audio.paused?' playing-track':'');wrap.innerHTML=`<span class="thumb">${thumbSVG()}</span><span><span class="title">${t.title}</span><span class="tiny">${t.artist||'Local file'}</span></span><span style="display:flex;gap:8px;align-items:center"><button class="mini" data-del="${i}" style="border:1px solid var(--border);background:var(--panel2);color:var(--text);border-radius:12px;padding:8px 10px;cursor:pointer">Delete</button><span class="tiny">Play</span></span>`;wrap.querySelector('[data-del]').onclick=e=>{e.stopPropagation(); deleteTrack(i)};wrap.onclick=()=>loadTrack(i,true);playlistEl.appendChild(wrap)});if(!items.length)playlistEl.innerHTML='<div class="tiny">No tracks match your search.</div>'}
function deleteTrack(i){const was=current===i;playlist.splice(i,1);if(current>i)current--;if(!playlist.length){current=-1;audio.removeAttribute('src');play.textContent='▶';nowTitle.textContent='No track loaded';nowArtist.textContent='Choose one or drop your files in.';body.classList.remove('playing');setMsg('Playlist is empty',true);renderPlaylist();return}if(was)current=Math.min(i,playlist.length-1);renderPlaylist();if(was)loadTrack(current,true);else setMsg('Track deleted',true)}
function loadTrack(i,auto=false){current=i;const t=playlist[current];audio.src=t.url;nowTitle.textContent=t.title;nowArtist.textContent=t.artist||'Local file';seek.value=0;timeNow.textContent='0:00';timeTotal.textContent='0:00';renderPlaylist();setMsg('Track loaded',true);if(auto)playTrack()}
async function playTrack(){if(!audio.src&&playlist.length)loadTrack(0,false);ensureCtx();if(audioCtx.state==='suspended')await audioCtx.resume();try{await audio.play();play.textContent='❚❚';play.classList.add('playing');body.classList.add('playing');setMsg('Playing',true);state.textContent='Playing'}catch(e){setMsg('Could not play this file',false)}}
play.onclick=()=>audio.paused?playTrack():(audio.pause(),play.textContent='▶',play.classList.remove('playing'),body.classList.remove('playing'),setMsg('Paused',true),state.textContent='Paused');
prev.onclick=()=>playlist.length&&loadTrack((current-1+playlist.length)%playlist.length,true); next.onclick=()=>playlist.length&&loadTrack((current+1)%playlist.length,true);
audio.addEventListener('loadedmetadata',()=>{timeTotal.textContent=fmt(audio.duration);state.textContent='Loaded'}); audio.addEventListener('timeupdate',()=>{timeNow.textContent=fmt(audio.currentTime);if(isFinite(audio.duration)&&audio.duration)seek.value=(audio.currentTime/audio.duration)*100;renderPlaylist()}); audio.addEventListener('ended',()=>next.onclick()); audio.addEventListener('play',()=>{play.textContent='❚❚';play.classList.add('playing');body.classList.add('playing');renderPlaylist()}); audio.addEventListener('pause',()=>{play.textContent='▶';play.classList.remove('playing');body.classList.remove('playing');renderPlaylist()}); audio.addEventListener('error',()=>setMsg('This audio file could not play',false));
seek.addEventListener('input',()=>{if(isFinite(audio.duration))audio.currentTime=(seek.value/100)*audio.duration}); volume.addEventListener('input',()=>{audio.volume=volume.value;volTxt.textContent=`${Math.round(volume.value*100)}%`}); audio.volume=volume.value;
function addFiles(files){const list=[...files];if(!list.length)return;list.forEach(file=>playlist.push({title:file.name.replace(/\.[^.]+$/,''),artist:'Local file',url:URL.createObjectURL(file)}));renderPlaylist();if(current===-1)loadTrack(0,false)}
fileInput.onchange=()=>addFiles(fileInput.files);
window.addEventListener('dragover',e=>{e.preventDefault();dropzone.classList.add('drag');dropBar.style.width='100%';state.textContent='Drop files to add'}); window.addEventListener('dragleave',()=>{dropzone.classList.remove('drag');dropBar.style.width='0%'}); window.addEventListener('drop',e=>{e.preventDefault();dropzone.classList.remove('drag');dropBar.style.width='0%';if(e.dataTransfer.files&&e.dataTransfer.files.length)addFiles(e.dataTransfer.files)});
searchFilter.addEventListener('input',renderPlaylist);
themeBtn.onclick=()=>{theme=theme==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',theme);themeBtn.textContent=theme==='dark'?'☀':'☾'};
renderEq(); renderPlaylist();